services:
  serverrestart:
    build:
      context: .
      target: final
    volumes:
      - ~/restart_configs:/etc/restart_configs:U
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CONFIG_PATH=/etc/restart_configs
